/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Gumball } from "./Gumball";
export * as factories from "./factories";
export { Gumball__factory } from "./factories/Gumball__factory";
